workflows:
  android-apk-free:
    name: Android APK Build
    environment:
      vars:
        BUNDLE: "false"
        #GH_REPO: ""  # Optional: override target repository
        GH_TOKEN: "${CM_GH_TOKEN}"  # Optional: GitHub token
    scripts:
      - name: Setup and Build
        script: |
          flutter packages pub get
          
          # Decode keystore if available
          if [ -f "android/keystore.base64" ]; then
            base64 -d android/keystore.base64 > android/app/mahakka.keystore
          fi
          
          # Build with signing if possible
          if [ -f "mahakka.keystore" ] && [ -n "$CM_KEYSTORE_PASSWORD" ]; then
            flutter build apk --release \
              --keystore="android/app/mahakka.keystore" \
              --store-password="$CM_KEYSTORE_PASSWORD" \
              --key-alias="${CM_KEY_ALIAS:-mahakka}" \
              --key-password="${CM_KEY_PASSWORD:-$CM_KEYSTORE_PASSWORD}"
          else
            flutter build apk --release
          fi

      - name: Create GitHub Release with curl
        script: |
          # Create GitHub release using curl (no gh CLI needed)
          APK_FILE=$(find build/app/outputs/flutter-apk -name "*.apk" | head -n 1)
          
          if [ -z "$APK_FILE" ]; then
            echo "❌ No APK file found for release!"
            exit 1
          fi
          
          echo "📦 Creating GitHub release for: $APK_FILE"
          
          # Auto-detect repository from git remote
          AUTO_REPO=$(git remote -v | head -n 1 | sed -E 's/.*github.com[:\/]([^\.]+).*/\1/')
          
          # Use override repo if provided, otherwise auto-detect
          TARGET_REPO="${GH_REPO:-$AUTO_REPO}"
          
          if [ -z "$TARGET_REPO" ]; then
            echo "❌ Could not determine GitHub repository"
            echo "   Either set GH_REPO environment variable or ensure git remote is configured"
            exit 1
          fi
          
          echo "🏷️  Target repository: $TARGET_REPO"
          
          # Get GitHub token (use provided token or try CodeMagic's token)
          GITHUB_TOKEN="${GH_TOKEN:-$CM_GH_TOKEN}"
          
          if [ -z "$GITHUB_TOKEN" ]; then
            echo "❌ GitHub token is required for creating releases with curl"
            echo "   Please set GH_TOKEN environment variable in CodeMagic"
            exit 1
          fi
          
          APK_NAME=$(basename "$APK_FILE")
          RELEASE_TAG="v$CM_BUILD_NUMBER"
          RELEASE_NAME="Release v$CM_BUILD_NUMBER"
          
          # Create release
          echo "🚀 Creating release $RELEASE_TAG..."
          RELEASE_RESPONSE=$(curl -s -w "%{http_code}" -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Content-Type: application/json" \
            "https://api.github.com/repos/$TARGET_REPO/releases" \
            -d "{
              \"tag_name\": \"$RELEASE_TAG\",
              \"name\": \"$RELEASE_NAME\",
              \"body\": \"Automated build from CodeMagic\\n- Build Number: $CM_BUILD_NUMBER\\n- Commit: $(git log -1 --pretty=%B | head -n 1)\\n- Date: $(date -u +'%Y-%m-%d %H:%M:%S UTC')\",
              \"draft\": false,
              \"prerelease\": false
            }")
          
          # Extract HTTP status code and response body
          HTTP_STATUS=${RELEASE_RESPONSE: -3}
          RESPONSE_BODY=${RELEASE_RESPONSE%???}
          
          if [ "$HTTP_STATUS" -ne 201 ]; then
            echo "❌ Failed to create release (HTTP $HTTP_STATUS)"
            echo "Response: $RESPONSE_BODY"
            exit 1
          fi
          
          UPLOAD_URL=$(echo "$RESPONSE_BODY" | grep -o '"upload_url": "[^"]*' | cut -d'"' -f4 | sed 's/{.*}//')
          RELEASE_ID=$(echo "$RESPONSE_BODY" | grep -o '"id": [0-9]*' | cut -d' ' -f2)
          
          if [ -z "$UPLOAD_URL" ] || [ -z "$RELEASE_ID" ]; then
            echo "❌ Failed to parse release response"
            echo "Response: $RESPONSE_BODY"
            exit 1
          fi
          
          echo "✅ Release created successfully (ID: $RELEASE_ID)"
          
          # Upload APK asset
          echo "📤 Uploading APK asset..."
          UPLOAD_RESPONSE=$(curl -s -w "%{http_code}" \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Content-Type: application/vnd.android.package-archive" \
            --data-binary "@$APK_FILE" \
            "$UPLOAD_URL?name=$APK_NAME")
          
          UPLOAD_STATUS=${UPLOAD_RESPONSE: -3}
          UPLOAD_BODY=${UPLOAD_RESPONSE%???}
          
          if [ "$UPLOAD_STATUS" -ne 201 ]; then
            echo "❌ Failed to upload asset (HTTP $UPLOAD_STATUS)"
            echo "Response: $UPLOAD_BODY"
            exit 1
          fi
          
          DOWNLOAD_URL=$(echo "$UPLOAD_BODY" | grep -o '"browser_download_url": "[^"]*' | cut -d'"' -f4)
          
          if [ -n "$DOWNLOAD_URL" ]; then
            echo "✅ Release created successfully!"
            echo "📥 Download URL: $DOWNLOAD_URL"
          else
            echo "⚠️  Release created but could not get download URL"
            echo "Release page: https://github.com/$TARGET_REPO/releases/tag/$RELEASE_TAG"
          fi

    artifacts:
      - build/app/outputs/flutter-apk/*.apk

    publishing:
      email:
        recipients:
          - bitcoinizado@proton.me
        notify:
          success: true
          failure: true